openapi: 3.0.0
info:
  title: "Motorix API"
  version: 1.0.0
  description: "Open API doc for the Motorix API"
servers:
  - url: http://localhost:4941/api/v1
    description: "Your development server"
tags:
  - name: users
    description: "Endpoints for signing up, signing in, updating, and retrieving user information"
paths:
  /users/signup:
    post:
      tags:
        - users
      summary: "Sign up as a new user"
      description: "The email must be syntactically valid (e.g. it has to include an `@` and a top level domain for example `x@y.z`). Whether it is actually a registered email address will not be checked. The email address <b>must not</b> already be in use (if it is in use the server should return a 403). The password <b>must</b> be a minimum of 6 characters"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserSignUp"
      responses:
        201:
          description: "Created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserSignUpResponse"
        400:
          description: "Bad Request. Invalid information"
        403:
          description: "Forbidden. Email already in use"
        500:
          description: "Internal Sever Error"
          
components:
  schemas:
    UserSignUp:
      title: UserSignUp
      type: object
      properties:
        firstName:
          type: string
          minLength: 1
          maxLength: 50
          example: "John"
        lastName:
          type: string 
          minLength: 1 
          maxLength: 50
          example: "Doe"
        username:
          type: string 
          minLength: 1 
          maxLength: 50
          example: "TestUserOne"
        phoneNumber: 
          type: string
          minLength: 1
          maxLength: 12
          example: "02230684567"
        email: 
          type: string
          minLength: 1 
          maxLength: 255
          format: email
          example: "jdoe@example.com"
        password: 
          type: string 
          minLength: 1 
          maxLength: 255
          example: "password"
    UserSignUpResponse:
      title: UserSignUpResponse
      type: object
      properties:
        message:
          type: string
        userId:
          minLength: 36
          maxLength: 36

  securitySchemes:
    UserToken:
      type: apiKey
      name: X-Authorization
      in: header